### ISSUE TITLE
Can branchMover move private repos?

### ISSUE THREAD

**Issue by sellorm** [gadenbuie/branchMover#11]
`branchMover` fixed all my public repos like a champ, but I'm a bit confused about my private repos.

```
[main] > branchMover::app()

Listening on http://127.0.0.1:5644
ℹ @sellorm has 149 total repositories (including forks)
• 71 public repos
• 78 private reps
ℹ Found 30 branch mover issues:
✓ 30 are closed
ℹ 71 non-fork repositories have the following default branches:
✓ main: 71 repos
ℹ You have admin rights on 71 repos
```

This feels like it's telling me I don't have admin rights on my private repos. Or maybe I did something wrong or `branchMover` doesn't support private repos?? Could you clarify?

**Comment by gadenbuie** [comment]
Thanks @sellorm and yeah that is confusing. There were internal ways to turn on/off forks or private repos and I've made them more explicit now. I also added documentation in `?branchMover::app` that should clarify everything.

In short, I no longer include forked repos by default and if you're the authenticated gh user private repos are included in the app. (Previously there was a bug that private repos were never included because I needed to query a different endpoint for auth'ed users.)

Now, when running the app under my account I see

```
branchMover:main > app()

ℹ @gadenbuie has 259 total repositories (including forks)
• 227 public repos
• 32 private reps
ℹ Will include private repos
ℹ Will exclude forks
ℹ Found 30 branch mover issues:                 
✓ 30 are closed
ℹ 127 non-fork repositories have the following default branches:
x master: 46 repos
✓ main: 79 repos
! something else: 2 repos
ℹ You have admin rights on 127 repos
```

When running it for you (using my account for gh api access) I see

```
branchMover:main > app("sellorm")

ℹ @sellorm has 71 total repositories (including forks)
• 71 public repos
• 0 private reps
x branchMover cannot list private repos for users other than the authenticated user (@gadenbuie)
ℹ Will exclude forks and private repos
ℹ Found 30 branch mover issues:
✓ 30 are closed
ℹ 57 non-fork repositories have the following default branches:
✓ main: 57 repos
ℹ You have admin rights on 0 repos
```

**Comment by sellorm** [comment]
Thanks @gadenbuie - all of my repos are now moved and I'm very happy!
