### ISSUE TITLE
Be able to point the app at an organisation

### ISSUE THREAD

**Issue by jennybc** [gadenbuie/branchMover#6]
It would be pretty interesting to use the app to explore an organisation's repos vs. those I own personally.

I think it's akin to the optional `organisation ` argument in [`usethis::use_github()`](https://usethis.r-lib.org/reference/use_github.html).

**Comment by gadenbuie** [comment]
My intention was to allow the `username` argument (previously named `user`) of `app()` to pass through and be used everywhere, so something like

```r
branchMover::app("rstudio-education")
```

would work to find repos for an organization or user other than the authenticated user. It wasn't quite working because I was accidentally hitting `/user` rather than `/users/{username}` in a couple places, but that part should be fixed now.

I'll push another PR momentarily that will take into account whether the authenticated user as admin rights on the listed repos

**Comment by jennybc** [comment]
OK, yes, now I can run the app, for my account, as well as tidyverse and r-lib 🎉

I didn't realize `app()` already took an org name as an argument. I think you should document that somewhere, because the org use case is probably pretty common.
