### ISSUE TITLE
If working in temporary clone, no need for `usethis::git_default_branch_rename()`

### ISSUE THREAD

**Issue by jennybc** [gadenbuie/branchMover#9]
If you're not working out of the user's primary local copy, as this app does not, there is no need to clone the repo and call `usethis::git_default_branch_rename()`. You could just call the GitHub API directly and change the default branch. Here:

https://github.com/gadenbuie/branchMover/blob/c8162a41393035477ca91eefd64f2100fe2e698f/R/move_branch.R#L65-L77

I don't think you're gaining anything by cloning and, in fact, it's rather costly. There's the actual clone, which gets thrown away, plus you get into matters of SSH vs HTTPS for the URL (currently I doubt this will work for someone w/o SSH keys).

**Comment by gadenbuie** [comment]
This is a great point, and one that I was planning on coming back to later. The fresh clone bugged me, too, and now that I added checking around admin privileges, we'd only miss out on reporting fishy files (in the command line messages) — unless you're saying `git_default_branch_rename()` would know we're not in the primary local copy and wouldn't report anyway.

I'll try swapping out the `git_default_branch_rename()` for a call to the GitHub API directly

**Comment by jennybc** [comment]
> we'd only miss out on reporting fishy files (in the command line messages) — unless you're saying `git_default_branch_rename()` would know we're not in the primary local copy and wouldn't report anyway.

Yeah, you are going to miss out on that. I haven't used your app to actually change a branch, so I was unclear whether the app was actually transmitting those messages to the user anyway.

You could:
* Use the API to change default branch.
* Open the issue, encouraging the user to search for `"master"` and `"main"`.
* Leave the issue open?

**Comment by jennybc** [comment]
But if you continue to clone, you have to grapple with the HTTPS vs SSH URL problem.

**Comment by gadenbuie** [comment]
> so I was unclear whether the app was actually transmitting those messages to the user anyway.

It was "transmitted" in the sense I was expecting users to have the R console open at the same time to see the output of `git_default_branch_rename()` there. That's probably not super helpful, so I went ahead and switched to using the GitHub API directly.

The default issue message I wrote includes a link to search for the word "master" in the repo being changed. I could probably provide a stronger nudge... but I did add another option for users to control whether the issue is left open or is closed automatically if everything goes okay or if the issue is left open. I changed the default behavior (just now after merging the PR) so that the issue is left open by default. The "Change Default Branch" button then becomes "Finalize Change".

Thanks for your suggestions and advice, they've been very helpful!
